In [1]:
import tensorflow as tf

In [2]:
# paragraph
def p(*objects, last=True):
    print(*objects, sep='\n'*2, end='\n'*2**(not last))

#### Tensors with the same constant values

In [3]:
ze2 = tf.zeros(2)
on3x5 = tf.ones((3, 5))
tw2x3x5 = tf.fill((2, 3, 5), value=2.)
p('Vector (rank-1 tensor)', ze2,
  'Matrix (rank-2 tensor)', on3x5,
  'Rank-3 tensor', tw2x3x5)

Vector (rank-1 tensor)

tf.Tensor([0. 0.], shape=(2,), dtype=float32)

Matrix (rank-2 tensor)

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(3, 5), dtype=float32)

Rank-3 tensor

tf.Tensor(
[[[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]], shape=(2, 3, 5), dtype=float32)


#### Tensors with random values

In [4]:
ru2x3 = tf.random.uniform((2, 3), minval=0, maxval=1)
rn2x3 = tf.random.normal((5, 2), mean=0, stddev=1)
rtn2x3 = tf.random.truncated_normal((3, 5), mean=0, stddev=1)
p('Matrix with random uniform values', ru2x3,
  'Matrix with random normal values', rn2x3,
  'Matrix with truncated random normal values', rtn2x3)

Matrix with random uniform values

tf.Tensor(
[[0.18165445 0.19296658 0.5878961 ]
 [0.10600185 0.7134507  0.83647573]], shape=(2, 3), dtype=float32)

Matrix with random normal values

tf.Tensor(
[[ 1.1915098   1.6910524 ]
 [-0.8505281   1.6118783 ]
 [ 0.4714488  -0.04704379]
 [ 0.7273828   1.0534209 ]
 [-0.6943145  -0.2530615 ]], shape=(5, 2), dtype=float32)

Matrix with truncated random normal values

tf.Tensor(
[[ 0.48320144 -0.94951314  0.18423975  0.27844903  0.05910079]
 [-0.08474454 -0.70819163  0.66125983  0.39343864 -0.2995215 ]
 [-0.44130096 -0.87078136 -1.4468027  -0.8293213  -1.8098135 ]], shape=(3, 5), dtype=float32)


#### Tensor addition and elementwise multiplication

In [5]:
tw2x3 = tf.fill((2, 3), value=2.)
th2x3 = tf.fill((2, 3), value=3.)
p('Input matrices', tw2x3, th2x3,
  'Addition', tw2x3 + th2x3,
  'Elementwise multiplication', tw2x3 * th2x3, 5 * tw2x3)

Input matrices

tf.Tensor(
[[2. 2. 2.]
 [2. 2. 2.]], shape=(2, 3), dtype=float32)

tf.Tensor(
[[3. 3. 3.]
 [3. 3. 3.]], shape=(2, 3), dtype=float32)

Addition

tf.Tensor(
[[5. 5. 5.]
 [5. 5. 5.]], shape=(2, 3), dtype=float32)

Elementwise multiplication

tf.Tensor(
[[6. 6. 6.]
 [6. 6. 6.]], shape=(2, 3), dtype=float32)

tf.Tensor(
[[10. 10. 10.]
 [10. 10. 10.]], shape=(2, 3), dtype=float32)


#### Diagonal matrices

In [6]:
eye2 = tf.eye(2)
diag_th5 = tf.linalg.diag([3.]*5)
p('Identity matrix', eye2,
  'Diagonal matrix', diag_th5)

Identity matrix

tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)

Diagonal matrix

tf.Tensor(
[[3. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 3.]], shape=(5, 5), dtype=float32)


#### Matrix transpose

In [7]:
tw3x2 = tf.linalg.matrix_transpose(tw2x3)
p('Input matrix', tw2x3,
  'Transpose', tw3x2)

Input matrix

tf.Tensor(
[[2. 2. 2.]
 [2. 2. 2.]], shape=(2, 3), dtype=float32)

Transpose

tf.Tensor(
[[2. 2.]
 [2. 2.]
 [2. 2.]], shape=(3, 2), dtype=float32)


#### Matrix multiplication

In [8]:
si2x5 = tf.linalg.matmul(tw2x3, on3x5)
p('Input matrices', tw2x3, on3x5,
  'Multiplication', si2x5)

Input matrices

tf.Tensor(
[[2. 2. 2.]
 [2. 2. 2.]], shape=(2, 3), dtype=float32)

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(3, 5), dtype=float32)

Multiplication

tf.Tensor(
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]], shape=(2, 5), dtype=float32)


#### Tensor reshaping

In [9]:
th1x2x3 = tf.expand_dims(th2x3, axis=0)
p('Input matrix', th2x3,
  'Reshaped matrix', tf.reshape(th2x3, (3, 2, 1)),
  'Matrix with the first dim expanded', th1x2x3, last=False)
th2x3 = tf.squeeze(th1x2x3)
p('Squeezed matrix', th2x3)

Input matrix

tf.Tensor(
[[3. 3. 3.]
 [3. 3. 3.]], shape=(2, 3), dtype=float32)

Reshaped matrix

tf.Tensor(
[[[3.]
  [3.]]

 [[3.]
  [3.]]

 [[3.]
  [3.]]], shape=(3, 2, 1), dtype=float32)

Matrix with the first dim expanded

tf.Tensor(
[[[3. 3. 3.]
  [3. 3. 3.]]], shape=(1, 2, 3), dtype=float32)

Squeezed matrix

tf.Tensor(
[[3. 3. 3.]
 [3. 3. 3.]], shape=(2, 3), dtype=float32)


#### Broadcasting

In [10]:
tw5 = tf.fill((5,), 2.)
th3x5 = tw5 + on3x5
p('Input matrices', tw5, on3x5,
  'Addition', th3x5)

Input matrices

tf.Tensor([2. 2. 2. 2. 2.], shape=(5,), dtype=float32)

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(3, 5), dtype=float32)

Addition

tf.Tensor(
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]], shape=(3, 5), dtype=float32)
